open-webui:
  image: {{< .Values.extra_tools.open_webui.webui.image | toJSON >}}
  ollama:
    enabled: {{< .Values.extra_tools.open_webui.ollama.enabled | conv.ToBool >}}
    image:
      tag: {{< .Values.extra_tools.open_webui.ollama.version >}}
    replicaCount: {{< .Values.extra_tools.open_webui.ollama.replicaCount >}}
    persistentVolume:
      enabled: {{< .Values.extra_tools.open_webui.ollama.persistentVolume.enabled | conv.ToBool >}}
      storageClass: {{< .Values.extra_tools.open_webui.ollama.persistentVolume.storageClass | quote >}}
      size: {{< .Values.extra_tools.open_webui.ollama.persistentVolume.size >}}
    updateStrategy:
      type: "Recreate"
    extraEnv:
      - name: OLLAMA_KEEP_ALIVE
        value: "-1"
    ollama:
      models: {{< .Values.extra_tools.open_webui.ollama.models >}}
      gpu:
        enabled: {{< .Values.extra_tools.open_webui.ollama.gpu.enabled | conv.ToBool >}}
        number: {{< .Values.extra_tools.open_webui.ollama.gpu.number | quote >}}
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClass: {{< .Values.extra_tools.open_webui.webui.persistence.storageClass | quote >}}
  extraEnvVars: {{< .Values.extra_tools.open_webui.webui.extraEnvVars | toJSON >}}

########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:
    {{<- range $manifest := .Values.deploykf_core.deploykf_auth.extraManifests >}}
    - {{< (tpl $manifest $) | quote >}}
    {{<- end >}}

  clusterDomain: cluster.local

  certManager:
    clusterIssuer:
      selfSigned:
        injectedConfigMapName: {{< .Values.deploykf_dependencies.cert_manager.clusterIssuer.selfSigned.injectedConfigMapName | quote >}}

  istio:
    namespace: {{< .Values.deploykf_dependencies.istio.namespace | quote >}}

  gateway:
    namespace: {{< .Values.deploykf_core.deploykf_istio_gateway.namespace | quote >}}
    serviceAccount: {{< .Values.deploykf_core.deploykf_istio_gateway.gatewayDeployment.serviceAccount.name | quote >}}
    name: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name | quote >}}
    hostname: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.hostname | quote >}}
    tls:
      enabled: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.tls.enabled | conv.ToBool >}}
      clientsUseHttps: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.tls.clientsUseHttps | conv.ToBool >}}